[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = [
  # "E501" # "line too long"
  "E402", # "import not at top of file"
  "E703", # "statement ends with a semicolon"
  "E731", # "do not assign a lambda expression, use a def"
  # "F401", # "imported but unused"
  # "F811", # "redefinition of unused name"
]
extend-select = [
  # "E501" # "line too long"
]

# unfixable = ["B"]

[tool.ruff.lint.per-file-ignores]
"Optimise*.py" = [
  "F401", # "imported but unused"
]
# "**/{tests,docs,tools}/*" = ["E402"]

# [tool.ruff.format]
# quote-style = "single"
